### ISSUE TITLE
docker: error pulling image configuration: unknown blob.

### ISSUE THREAD

**Issue by szabgab** [Tekki/docker-mojolicious#2]
I am not sure if this is an issue of my computer or something with the image:

```
$ docker container run --rm -v "$(pwd):/usr/src/app" tekki/mojolicious mojo generate app MyApp
Unable to find image 'tekki/mojolicious:latest' locally
latest: Pulling from tekki/mojolicious
57df1a1f1ad8: Already exists 
71e126169501: Already exists 
1af28a55c3f3: Already exists 
03f1c9932170: Already exists 
65b3db15f518: Already exists 
4c21f9be7406: Already exists 
c8090f4b73c1: Already exists 
89fed5b8575b: Pulling fs layer 
e41889ca2d25: Pulling fs layer 
0dde9e1cd4e0: Pulling fs layer 
91159e1713a1: Waiting 
docker: error pulling image configuration: unknown blob.
```

```
docker -v
Docker version 19.03.8, build afacb8b7f0
```

**Comment by hbarnard** [comment]
Yes, also have this error. Also, I'm a docker beginner, so worth having:
```
sudo systemctl start docker.service
sudo systemctl status docker.service
```
in the operating instructions.

**Comment by Tekki** [comment]
I can reproduce this. Now that I've pushed the images again to Dockerhub it seems to work. Could you please check?

**Comment by szabgab** [comment]
It worked for me. Thank you for the quick fix!

**Comment by Tekki** [comment]
> Yes, also have this error. Also, I'm a docker beginner, so worth having:
> 
> ```
> sudo systemctl start docker.service
> sudo systemctl status docker.service
> ```
> 
> in the operating instructions.

Don't agree with that. These are instructions about how to use this image, not how to use Docker itself.
It seems strange to me that you have docker installed but the service isn't enabled by default and you have to start it manually. Another point is that you can use this command only if you are on Linux. If you use Docker Desktop on Windows everything looks completely different.

**Comment by hbarnard** [comment]
OK. Meanwhile, the fix works, thanks. I actually have a ready made application that I'm looking to dockerise this: https://sourceforge.net/projects/cclite2/

**Comment by szabgab** [comment]
I am reposting my question as a new issue to keep this space cleaner.
