### ISSUE TITLE
my_app directory structure created as root

### ISSUE THREAD

**Issue by szabgab** [Tekki/docker-mojolicious#3]
Running

```
docker container run --rm -v "$(pwd):/usr/src/app" tekki/mojolicious mojo generate app MyApp
```
created all the my_app directory structure owned by `root` (Linux host).

Is this the expected behaviour is my Docker misconfigured?
Is there a way to create the files owned by the current user in the host, or shall I just chown-them myself?

**Comment by Tekki** [comment]
> created all the my_app directory structure owned by `root` (Linux host).

That's correct, by default a container created with this image runs a `root`. We inherit this from [docker-perl](https://github.com/Perl/docker-perl).
If you want to run it with any other user and group ID you can use the `-u` parameter:
```
docker container run --rm -u 1024:1099 -v "$(pwd):/usr/src/app" tekki/mojolicious mojo generate app MyApp
```
