### ISSUE TITLE
Q: User defined signal 2

### ISSUE THREAD

**Issue by KES777** [Tekki/docker-mojolicious#4]
Does this work well

    $ docker container run -d --rm -v "$(pwd):/usr/src/app" -p 8080:8080 tekki/mojolicious hypnotoad -f script/my_app

when host server got hard reset?

In my scenario at that case when I do `docker start my_container` I see at logs:

     [prod] User defined signal 2

and container exit

**Comment by Tekki** [comment]
If 'hard reset' means something like a power failure then it depends on your system how it will behave. Do you have this error message since such an event? Is the rest of Docker running fine?

**Comment by butter-x** [comment]
I have asked `sri`. He says that: hypnotoad is not meant for container. I am switched to `prefork` as this shown by `app generate dockerfile` command

**Comment by KES777** [comment]
I have asked `sri`. He says that: hypnotoad is not meant for container. I am switched to `prefork` as this shown by app generate dockerfile command

**Comment by Tekki** [comment]
> I have asked `sri`. He says that...

So I can expect a pull request to improve the readme, @KES777 ?

**Comment by KES777** [comment]
use this command to generate example `Dockerfile`: https://docs.mojolicious.org/Mojolicious/Command/Author/generate/dockerfile
